name: MNemoLink builds
permissions: write-all

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build-linux:
    name: Build for Linux
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4
      - name: Install flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true
          architecture: x64
      - name: Ubuntu dependencies 
        run: |
          sudo apt-get update -y
          sudo apt-get install -y ninja-build libgtk-3-dev
      - name: Enable flutter desktop (linux)
        run: flutter config --enable-linux-desktop
      - name: Build (Linux)
        run: flutter build linux
        
  build-mac:
    name: Build for MacOS
    runs-on: macos-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4
      - name: Install flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true
          architecture: x64
      - name: MacOS dependencies
        run: brew install automake libtool
      - name: Enable flutter desktop (MacOS)
        run: flutter config --enable-macos-desktop
      - name: Build (MacOS)
        run: flutter build macos
        
  build-windows:
    name: Build for Windows
    runs-on: windows-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4
      - name: Install flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true
          architecture: x64
      - name: Enable flutter desktop (Windows)
        run: flutter config --enable-windows-desktop
      - name: Build (Windows)
        run: flutter build windows

  build-android:
    name: Build for Android
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4
      - name: Setup Java 
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
      - name: Install flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true
          architecture: x64
      - name: Build (Android APK)
        run: flutter build apk --debug
      - name: Build (Android Appbundle)
        run: flutter build appbundle --debug
